# Generated by Django 4.2.10 on 2024-02-07 06:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master_data", "0002_product_qtypcsperdus"),
    ]

    operations = [
        migrations.CreateModel(
            name="PengeluaranBarangHeader",
            fields=[
                ("TrxOutPk", models.AutoField(primary_key=True, serialize=False)),
                (
                    "TrxOutNo",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("TrxOutDate", models.DateField(default=datetime.date.today)),
                ("TrxOutNotes", models.TextField(blank=True, null=True)),
                ("Update_At", models.DateTimeField(auto_now=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                (
                    "TrxOutSuppIdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pengeluaran_header",
                        to="master_data.supplier",
                    ),
                ),
                (
                    "WhsIdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pengeluaran_header",
                        to="master_data.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PengeluaranBarangDetail",
            fields=[
                ("TrxOutDPK", models.AutoField(primary_key=True, serialize=False)),
                ("TrxOutDQtyDus", models.IntegerField(default=0)),
                ("TrxOutDQtyPcs", models.IntegerField(blank=True)),
                ("Update_At", models.DateTimeField(auto_now=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                (
                    "TrxOutDProductIdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pengeluaran_detail",
                        to="master_data.product",
                    ),
                ),
                (
                    "TrxOutIDF",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Pengeluaran_detail",
                        to="transactions.pengeluaranbarangheader",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PenerimaanBarangHeader",
            fields=[
                ("TrxInPk", models.AutoField(primary_key=True, serialize=False)),
                (
                    "TrxInNo",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("TrxInDate", models.DateField(default=datetime.date.today)),
                ("TrxInNotes", models.TextField(blank=True, null=True)),
                ("Update_At", models.DateTimeField(auto_now=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                (
                    "TrxInSuppIdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Penerimaan_header",
                        to="master_data.supplier",
                    ),
                ),
                (
                    "WhsIdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Penerimaan_header",
                        to="master_data.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PenerimaanBarangDetail",
            fields=[
                ("TrxInDPK", models.AutoField(primary_key=True, serialize=False)),
                ("TrxInDQtyDus", models.IntegerField(default=0)),
                ("TrxInDQtyPcs", models.IntegerField(blank=True)),
                ("Update_At", models.DateTimeField(auto_now=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
                (
                    "TrxInDProductIdf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Penerimaan_detail",
                        to="master_data.product",
                    ),
                ),
                (
                    "TrxInIDF",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Penerimaan_detail",
                        to="transactions.penerimaanbarangheader",
                    ),
                ),
            ],
        ),
    ]
