# Generated by Django 4.2.10 on 2024-02-07 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penerimaanbarangdetail",
            name="TrxInIDF",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Penerimaan_detail",
                to="transactions.penerimaanbarangheader",
            ),
        ),
        migrations.AlterField(
            model_name="pengeluaranbarangdetail",
            name="TrxOutIDF",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Pengeluaran_detail",
                to="transactions.pengeluaranbarangheader",
            ),
        ),
    ]
