# Generated by Django 4.2.10 on 2024-02-07 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0002_product_qtypcsperdus"),
        ("transactions", "0002_alter_penerimaanbarangdetail_trxinidf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pengeluaranbarangheader",
            name="TrxOutSuppIdf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Pengeluaran_header",
                to="master_data.customer",
            ),
        ),
    ]
