# Generated by Django 4.2.10 on 2024-02-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("CustomerPk", models.AutoField(primary_key=True, serialize=False)),
                ("CustomerName", models.CharField(max_length=255, unique=True)),
                ("Update_At", models.DateTimeField(auto_now=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("ProductPk", models.AutoField(primary_key=True, serialize=False)),
                ("ProductName", models.CharField(max_length=255, unique=True)),
                ("Update_At", models.DateTimeField(auto_now=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("SupplierPk", models.AutoField(primary_key=True, serialize=False)),
                ("SupplierName", models.CharField(max_length=255, unique=True)),
                ("Update_At", models.DateTimeField(auto_now=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("WhsPk", models.AutoField(primary_key=True, serialize=False)),
                ("WhsName", models.CharField(max_length=255, unique=True)),
                ("Update_At", models.DateTimeField(auto_now=True)),
                ("Created_At", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
