# Generated by Django 4.2.10 on 2024-02-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="QtyPcsPerDus",
            field=models.IntegerField(default=1),
        ),
    ]
